In [1]:
import numpy as np
import scipy.linalg as la

In [11]:
list = [1,2,3]
print(list[0%3])

1


In [12]:
def partial_transpose(rho, subsystem_dims, system_to_transpose):
    """
    Compute the partial transpose of a density matrix with respect to one subsystem.
    
    Parameters:
    rho (np.ndarray): The density matrix of the quantum state.
    subsystem_dims (tuple): The dimensions of the subsystems.
    system_to_transpose (int): The subsystem (0 or 1) to perform the partial transpose on.
    
    Returns:
    np.ndarray: The partially transposed density matrix.
    """
    # Reshape the density matrix into a 4D tensor
    rho_tensor = np.reshape(rho, subsystem_dims + subsystem_dims)
    
    if system_to_transpose == 0:
        # Transpose the first subsystem (swap axes 1 and 2)
        rho_tensor = np.transpose(rho_tensor, (1, 0, 3, 2))
    else:
        # Transpose the second subsystem (swap axes 0 and 3)
        rho_tensor = np.transpose(rho_tensor, (1,2,3,0))
    
    # Reshape back into a 2D matrix
    return np.reshape(rho_tensor, (np.prod(subsystem_dims), np.prod(subsystem_dims)))

In [13]:
def is_entangled(density_matrix, subsystem_dims):
    """
    Check if a given density matrix is entangled or free using the PPT criterion.
    
    Parameters:
    density_matrix (np.ndarray): The density matrix of the quantum state.
    subsystem_dims (tuple): The dimensions of the subsystems, e.g., (2, 2) for a 2-qubit system.
    
    Returns:
    bool: True if the state is entangled, False if it is free (separable).
    """
    # Perform the partial transpose on the first subsystem
    rho_partial_transpose = partial_transpose(density_matrix, subsystem_dims, 1)
    
    # Compute the eigenvalues of the partially transposed matrix
    eigenvalues = la.eigvalsh(rho_partial_transpose)
    
    # If any eigenvalue is negative, the state is entangled
    if np.any(eigenvalues < 0):
        return True  # Entangled
    else:
        return False  # Separable (Free)

In [14]:
bell_state = np.array([[0, 0, 0, 0],
                       [0, 0.5, 0.5, 0],
                       [0, 0.5, 0.5, 0],
                       [0, 0, 0, 0]])

In [15]:
is_entangled_state = is_entangled(bell_state, (2, 2))
print("Is the state entangled?", is_entangled_state)

Is the state entangled? True


In [16]:
bell = bell_state

In [17]:
bell = bell.reshape(2,2,2,2)
print(bell)
print("-------")
print(bell[0][0][0])
bell[0][0][1] = bell[0][1][0]
print("------")
print(bell)

[[[[0.  0. ]
   [0.  0. ]]

  [[0.  0.5]
   [0.5 0. ]]]


 [[[0.  0.5]
   [0.5 0. ]]

  [[0.  0. ]
   [0.  0. ]]]]
-------
[0. 0.]
------
[[[[0.  0. ]
   [0.  0.5]]

  [[0.  0.5]
   [0.5 0. ]]]


 [[[0.  0.5]
   [0.5 0. ]]

  [[0.  0. ]
   [0.  0. ]]]]


In [18]:
print("1",bell.transpose(0,1,2,3).reshape(4,4))
print("2",bell.transpose(0,1,3,2).reshape(4,4))
print("3",bell.transpose(0,2,1,3).reshape(4,4))
print("4",bell.transpose(1,2,3,0).reshape(4,4))

1 [[0.  0.  0.  0.5]
 [0.  0.5 0.5 0. ]
 [0.  0.5 0.5 0. ]
 [0.  0.  0.  0. ]]
2 [[0.  0.  0.  0.5]
 [0.  0.5 0.5 0. ]
 [0.  0.5 0.5 0. ]
 [0.  0.  0.  0. ]]
3 [[0.  0.  0.  0.5]
 [0.  0.5 0.5 0. ]
 [0.  0.5 0.  0. ]
 [0.5 0.  0.  0. ]]
4 [[0.  0.  0.  0.5]
 [0.  0.5 0.5 0. ]
 [0.  0.  0.5 0. ]
 [0.5 0.  0.  0. ]]


In [19]:
#https://stackoverflow.com/questions/32034237/how-does-numpys-transpose-method-permute-the-axes-of-an-array

In [20]:
arr = np.arange(1,5)

In [21]:
print(arr)

[1 2 3 4]


In [22]:
arr = arr.reshape(2,2)
print(arr)

[[1 2]
 [3 4]]


In [23]:
arr.transpose(1,0)

array([[1, 3],
       [2, 4]])

In [24]:
bell = np.arange(16).reshape(2,2,2,2).transpose(0,1,3,2)
print(bell)

[[[[ 0  2]
   [ 1  3]]

  [[ 4  6]
   [ 5  7]]]


 [[[ 8 10]
   [ 9 11]]

  [[12 14]
   [13 15]]]]


In [25]:
bell2 = np.arange(16)
print(bell2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [26]:
bell2 = bell2.reshape(2,2,2,2)
print(bell2)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [27]:
print(np.reshape(bell2,(4,4)))
firstbell = bell2.transpose(0,2,1,3)
print(np.reshape(firstbell,(4,4)))
midbell = firstbell.transpose(0,1,3,2)
print(np.reshape(midbell,(4,4)))
print(np.reshape(midbell.transpose(0,2,1,3),(4,4)))
newbell = midbell.transpose(0,2,1,3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  4  5]
 [ 2  3  6  7]
 [ 8  9 12 13]
 [10 11 14 15]]
[[ 0  4  1  5]
 [ 2  6  3  7]
 [ 8 12  9 13]
 [10 14 11 15]]
[[ 0  4  2  6]
 [ 1  5  3  7]
 [ 8 12 10 14]
 [ 9 13 11 15]]


In [28]:
newbell.reshape(4,4)

array([[ 0,  4,  2,  6],
       [ 1,  5,  3,  7],
       [ 8, 12, 10, 14],
       [ 9, 13, 11, 15]])

In [29]:
def ppt(state):
    re_state = state.reshape(2,2,2,2)
    mid_state = re_state.transpose(0,2,1,3).transpose(0,1,3,2)
    new = mid_state.transpose(0,2,1,3)
    ppt = new.reshape(4,4)
    return ppt

In [30]:
ppt(bell2)

array([[ 0,  4,  2,  6],
       [ 1,  5,  3,  7],
       [ 8, 12, 10, 14],
       [ 9, 13, 11, 15]])

In [31]:
def is_ent(state):
    part = ppt(state)
    print(part)
    print("______")
    eigenvalues = la.eigvalsh(part)
    print(eigenvalues)
    print("_______")
    
    # If any eigenvalue is negative, the state is entangled
    if np.any(eigenvalues < 0):
        return True  # Entangled
    else:
        return False  # Separable (Free)

In [32]:
print(is_ent(bell2))

[[ 0  4  2  6]
 [ 1  5  3  7]
 [ 8 12 10 14]
 [ 9 13 11 15]]
______
[-9.78100759  0.69492233  1.51545346 37.57063181]
_______
True


In [33]:
print(is_ent(bell_state))

[[0.  0.  0.  0.5]
 [0.  0.5 0.5 0. ]
 [0.  0.  0.5 0. ]
 [0.5 0.  0.  0. ]]
______
[-0.5  0.5  0.5  0.5]
_______
True


In [34]:
einheit = np.identity(4)

In [35]:
print(is_ent(einheit))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
______
[1. 1. 1. 1.]
_______
False


In [36]:
m1 = np.eye(3,3)

In [37]:
m2 = np.arange(1,10).reshape(3,3)

In [38]:
np.tensordot(m1,m2.T,0).transpose(0,2,1,3).reshape(9,9).trace()

45.0

In [48]:
np.tensordot(m1,m2.T,0).transpose(0,2,1,3).reshape

array([[[[1., 4., 7.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[2., 5., 8.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[3., 6., 9.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [1., 4., 7.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [2., 5., 8.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [3., 6., 9.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [1., 4., 7.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [2., 5., 8.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [3., 6., 9.]]]])

In [71]:
M = np.arange(1,82).reshape(3,3,3,3).reshape(9,9)
print(M)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]
 [55 56 57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70 71 72]
 [73 74 75 76 77 78 79 80 81]]


In [80]:
print(M.reshape(3,3,3,3).transpose(0,2,1,3).transpose(0,1,3,2).transpose(0,2,1,3).reshape(9,9))


[[ 1 10 19  4 13 22  7 16 25]
 [ 2 11 20  5 14 23  8 17 26]
 [ 3 12 21  6 15 24  9 18 27]
 [28 37 46 31 40 49 34 43 52]
 [29 38 47 32 41 50 35 44 53]
 [30 39 48 33 42 51 36 45 54]
 [55 64 73 58 67 76 61 70 79]
 [56 65 74 59 68 77 62 71 80]
 [57 66 75 60 69 78 63 72 81]]


In [84]:
def parttran(matrix):
    return matrix.reshape(3,3,3,3).transpose(0,2,1,3).transpose(0,1,3,2).transpose(0,2,1,3).reshape(9,9)

In [85]:
parttran(M)

array([[ 1, 10, 19,  4, 13, 22,  7, 16, 25],
       [ 2, 11, 20,  5, 14, 23,  8, 17, 26],
       [ 3, 12, 21,  6, 15, 24,  9, 18, 27],
       [28, 37, 46, 31, 40, 49, 34, 43, 52],
       [29, 38, 47, 32, 41, 50, 35, 44, 53],
       [30, 39, 48, 33, 42, 51, 36, 45, 54],
       [55, 64, 73, 58, 67, 76, 61, 70, 79],
       [56, 65, 74, 59, 68, 77, 62, 71, 80],
       [57, 66, 75, 60, 69, 78, 63, 72, 81]])