In [1]:
from Func_Col import *
import numpy as np

In [2]:
print(stvec)

[array([1.+0.j, 0.+0.j, 0.+0.j]), array([0.+0.j, 1.+0.j, 0.+0.j]), array([0.+0.j, 0.+0.j, 1.+0.j])]


In [3]:
for m in range(3):
    for n in range(3):
        print(f"{m},{n}")
        print(bell_con(m,n))

0,0
[0.57735027+0.j 0.        +0.j 0.        +0.j 0.        +0.j
 0.57735027+0.j 0.        +0.j 0.        +0.j 0.        +0.j
 0.57735027+0.j]
0,1
[ 0.57735027+0.j   0.        +0.j   0.        +0.j   0.        +0.j
 -0.28867513+0.5j  0.        +0.j   0.        +0.j   0.        +0.j
 -0.28867513-0.5j]
0,2
[ 0.57735027+0.j   0.        +0.j   0.        +0.j   0.        +0.j
 -0.28867513-0.5j  0.        +0.j   0.        +0.j   0.        +0.j
 -0.28867513+0.5j]
1,0
[0.        +0.j 0.57735027+0.j 0.        +0.j 0.        +0.j
 0.        +0.j 0.57735027+0.j 0.57735027+0.j 0.        +0.j
 0.        +0.j]
1,1
[ 0.        +0.j   0.57735027+0.j   0.        +0.j   0.        +0.j
  0.        +0.j  -0.28867513+0.5j -0.28867513-0.5j  0.        +0.j
  0.        +0.j ]
1,2
[ 0.        +0.j   0.57735027+0.j   0.        +0.j   0.        +0.j
  0.        +0.j  -0.28867513-0.5j -0.28867513+0.5j  0.        +0.j
  0.        +0.j ]
2,0
[0.        +0.j 0.        +0.j 0.57735027+0.j 0.57735027+0.j
 0.        +0

In [4]:
bell_states = bell_state()
print(bell_states)

[array([0.57735027+0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
       0.57735027+0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
       0.57735027+0.j]), array([ 0.57735027+0.j ,  0.        +0.j ,  0.        +0.j ,
        0.        +0.j , -0.28867513+0.5j,  0.        +0.j ,
        0.        +0.j ,  0.        +0.j , -0.28867513-0.5j]), array([ 0.57735027+0.j ,  0.        +0.j ,  0.        +0.j ,
        0.        +0.j , -0.28867513-0.5j,  0.        +0.j ,
        0.        +0.j ,  0.        +0.j , -0.28867513+0.5j]), array([0.        +0.j, 0.57735027+0.j, 0.        +0.j, 0.        +0.j,
       0.        +0.j, 0.57735027+0.j, 0.57735027+0.j, 0.        +0.j,
       0.        +0.j]), array([ 0.        +0.j ,  0.57735027+0.j ,  0.        +0.j ,
        0.        +0.j ,  0.        +0.j , -0.28867513+0.5j,
       -0.28867513-0.5j,  0.        +0.j ,  0.        +0.j ]), array([ 0.        +0.j ,  0.57735027+0.j ,  0.        +0.j ,
        0.        +0.j ,  0.        +0.j , -0.288

In [5]:
d = dkl(1/5)
print(d)

[[0.4, 0, 0.1333333333333333], [0, 0.2, 0.1333333333333333], [0, 0, 0.1333333333333333]]


In [6]:
for m in range(3):
    for n in range(3):
        print(d[m][n]*bell_states[3*m+n])

[0.23094011+0.j 0.        +0.j 0.        +0.j 0.        +0.j
 0.23094011+0.j 0.        +0.j 0.        +0.j 0.        +0.j
 0.23094011+0.j]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j -0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.-0.j]
[ 0.07698004+0.j          0.        +0.j          0.        +0.j
  0.        +0.j         -0.03849002-0.06666667j  0.        +0.j
  0.        +0.j          0.        +0.j         -0.03849002+0.06666667j]
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
[ 0.        +0.j   0.11547005+0.j   0.        +0.j   0.        +0.j
  0.        +0.j  -0.05773503+0.1j -0.05773503-0.1j  0.        +0.j
  0.        +0.j ]
[ 0.        +0.j          0.07698004+0.j          0.        +0.j
  0.        +0.j          0.        +0.j         -0.03849002-0.06666667j
 -0.03849002+0.06666667j  0.        +0.j          0.        +0.j        ]
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
[ 0.+0.j  0.+0.j  0.+0.j -0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.-0.j  0.+0.j]
[ 0.        

In [7]:
print(rhob(0.5))

[ 0.48112522+0.j          0.19245009+0.j         -0.09622504+0.j
  0.04811252+0.08333333j  0.62546279+0.08333333j -0.09622504+0.33333333j
 -0.09622504-0.33333333j  0.04811252-0.08333333j  0.62546279-0.08333333j]


In [15]:
mom = [1,1,0,0.0]

l = lorentz_boost_k(mom)
print(l)
np.matmul(l,np.array([1,0,0,0]))


[[1.  1.  0.  0. ]
 [1.  1.5 0.  0. ]
 [0.  0.  1.  0. ]
 [0.  0.  0.  1. ]]


array([1., 1., 0., 0.])

In [9]:
vel = [0,0,1]
rap = 0.8

lam_boost(vel, rap)

array([[1.33743495, 0.        , 0.        , 0.88810598],
       [0.        , 1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        ],
       [0.88810598, 0.        , 0.        , 1.33743495]])

In [10]:
print(wigner(vel,rap,mom))

[[ 1.00000000e+00  0.00000000e+00  1.26150041e-01  6.64036770e-01]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-3.85464573e-16  0.00000000e+00  8.73849959e-01 -6.64036770e-01]
 [ 1.36325847e-16  0.00000000e+00  3.32018385e-01  7.47699918e-01]]
